version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/action/  # 이 디렉토리 내에 배포가 진행된다
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
      - chown ec2-user:ec2-user /home/ec2-user/action/scripts/deploy.sh
      - chmod +x /home/ec2-user/action/scripts/deploy.sh

  ApplicationStart:
    - location: /home/ec2-user/action/scripts/deploy.sh
      timeout: 60
      runas: ec2-user
