name: Java CI with Spring Boot

env:
  S3_BUCKET_NAME: task-tracker-1114

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Spring Boot
      run: ./gradlew bootJar

    # Access Key와 Secret Access Key를 통해 권한을 확인한다.
    # 아래 코드에 Access Key와 Secret Key를 직접 작성하지 않는다.
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ap-northeast-2

    # Move the JAR file to a dedicated directory
    - name: Prepare JAR file
      run: mkdir -p jar && mv build/libs/*.jar jar/

    # Upload JAR file to S3
    - name: Upload JAR to S3
      run: aws s3 cp --region ap-northeast-2 ./jar/ s3://$S3_BUCKET_NAME/

    # CodeDeploy에게 배포 명령을 내린다.
    - name: Code Deploy
      run: |
        aws deploy create-deployment --application-name task-tracker-code-deploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name task-tracker-code-group
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=jar/
