name: Add Reviewers
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository information
        uses: actions/checkout@v2
      - name: Get all team members
        uses: github/actions/get-users@v2
        with:
          filter: members
      - name: Add team members as reviewers
        run: |
          for user in ${{ steps.get-all-team-members.outputs.users }}; do
            gh pr review --add $user ${{ github.event.pull_request.head.ref }}
          done
