name: Reviewer Assign

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  reviewer-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            const reviewers = ["wise_JG", "gunsight1"];

            const pullRequest = await github.pulls.get('${{ github.event.pull_request.pull_id }}');

            for (const reviewer of reviewers) {
              await pullRequest.reviewers.add(reviewer);
            }

            const reviewComment = `리뷰어로 지정되었습니다.\n\n리뷰를 부탁드립니다.`;

            await pullRequest.comments.create({
              body: reviewComment,
            });
